//! Starter `.gitignore` seeding for folders dux initializes as repositories.
//!
//! Deliberate deviation from the "All settings are configurable" tenet, at the
//! user's explicit direction: this candidate list is a compile-time constant
//! that contributors extend via PR, not a config key. It seeds brand-new
//! repositories only, where there is no user intent to preserve, and a config
//! surface here would invite unreviewable divergence in what dux writes into
//! users' repos. Do not "fix" this by making it configurable.

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

use anyhow::{Context, Result, anyhow};

/// A directory dux offers to ignore when it initializes a repository, plus the
/// one-line explanatory comment written above its pattern.
pub struct IgnoreCandidate {
    /// Directory name relative to the repo root, without a trailing slash.
    pub dir: &'static str,
    /// One-line comment explaining why the directory is ignored.
    pub comment: &'static str,
}

/// Dependency and build-artifact directories only; nothing contentious (no
/// `.idea/`, no Go `vendor/`). Extend via pull request.
pub const STARTER_IGNORES: &[IgnoreCandidate] = &[
    IgnoreCandidate {
        dir: "node_modules",
        comment: "# Installed npm/yarn/pnpm packages; recreated from the lockfile.",
    },
    IgnoreCandidate {
        dir: "target",
        comment: "# Rust/Cargo build output; recreated by cargo build.",
    },
    IgnoreCandidate {
        dir: ".venv",
        comment: "# Python virtual environment; recreated from the project's dependency list.",
    },
    IgnoreCandidate {
        dir: "venv",
        comment: "# Python virtual environment; recreated from the project's dependency list.",
    },
    IgnoreCandidate {
        dir: "__pycache__",
        comment: "# Python bytecode cache; regenerated automatically.",
    },
    IgnoreCandidate {
        dir: "dist",
        comment: "# Packaged build output; recreated by the build tool.",
    },
    IgnoreCandidate {
        dir: "build",
        comment: "# Build output; recreated by the build tool.",
    },
    IgnoreCandidate {
        dir: ".next",
        comment: "# Next.js build cache; regenerated on the next build.",
    },
    IgnoreCandidate {
        dir: ".nuxt",
        comment: "# Nuxt build cache; regenerated on the next build.",
    },
    IgnoreCandidate {
        dir: ".terraform",
        comment: "# Terraform providers and modules; recreated by terraform init.",
    },
    IgnoreCandidate {
        dir: ".tox",
        comment: "# tox environments; recreated by tox.",
    },
    IgnoreCandidate {
        dir: ".mypy_cache",
        comment: "# mypy type-check cache; regenerated automatically.",
    },
    IgnoreCandidate {
        dir: ".pytest_cache",
        comment: "# pytest cache; regenerated automatically.",
    },
    IgnoreCandidate {
        dir: ".gradle",
        comment: "# Gradle caches; regenerated by the next Gradle run.",
    },
];

/// Candidates whose directory actually exists inside `dir`. Reads the
/// filesystem directly, so dot-named candidates are found even though the
/// project browser hides dotfolders.
pub fn matched_candidates(dir: &Path) -> Vec<&'static IgnoreCandidate> {
    STARTER_IGNORES
        .iter()
        .filter(|c| dir.join(c.dir).is_dir())
        .collect()
}

/// Append a commented starter block to `<repo>/.gitignore` covering the
/// matched candidates that are not already ignored. Returns `Ok(true)` iff it
/// wrote anything.
///
/// Must run after `git init` and before the initial commit: `check-ignore`
/// needs a repository, and an untracked `.gitignore` already filters
/// `git status` (both measured). The seed is deliberately not committed.
pub fn seed_gitignore(repo: &Path) -> Result<bool> {
    let matched = matched_candidates(repo);
    if matched.is_empty() {
        return Ok(false);
    }
    // Skip candidates a pre-existing .gitignore (or excludes file) already
    // covers. check-ignore exits 0 when ignored, 1 when not; any other outcome
    // keeps the candidate (a harmless duplicate beats a silently unfiltered
    // dependency tree).
    let kept: Vec<&IgnoreCandidate> = matched
        .into_iter()
        .filter(|c| {
            let already_ignored = Command::new("git")
                .arg("-C")
                .arg(repo)
                .args(["check-ignore", "-q", c.dir])
                .stdin(Stdio::null())
                .output()
                .map(|out| out.status.code() == Some(0))
                .unwrap_or(false);
            !already_ignored
        })
        .collect();
    if kept.is_empty() {
        return Ok(false);
    }
    let gitignore = repo.join(".gitignore");
    // No-follow write discipline (measured hazard): an append-open FOLLOWS a
    // .gitignore symlink and writes outside the repo, even through a dangling
    // link. Probe with symlink_metadata first and refuse anything that is not
    // a regular file or absent. The remaining probe-to-open TOCTOU window is
    // acceptable in this single-tenant trust model.
    let mut file = match std::fs::symlink_metadata(&gitignore) {
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            let mut opts = std::fs::OpenOptions::new();
            opts.write(true).create_new(true);
            opts.open(&gitignore)
                .with_context(|| format!("failed to create {}", gitignore.display()))?
        }
        Ok(meta) if meta.is_file() => {
            // Append-only: structurally incapable of truncating a .gitignore
            // that predates dux. If the existing bytes do not end in a
            // newline, write one first so the block never merges into the
            // user's last pattern.
            let existing = std::fs::read(&gitignore)
                .with_context(|| format!("failed to read {}", gitignore.display()))?;
            let mut opts = std::fs::OpenOptions::new();
            opts.append(true);
            let mut file = opts
                .open(&gitignore)
                .with_context(|| format!("failed to open {}", gitignore.display()))?;
            if !existing.is_empty() && !existing.ends_with(b"\n") {
                file.write_all(b"\n")
                    .with_context(|| format!("failed to write {}", gitignore.display()))?;
            }
            file
        }
        Ok(meta) => {
            let what = if meta.is_symlink() {
                "a symlink"
            } else if meta.is_dir() {
                "a directory"
            } else {
                "not a regular file"
            };
            return Err(anyhow!(
                "refusing to write {}: it is {}",
                gitignore.display(),
                what
            ));
        }
        Err(err) => {
            return Err(anyhow!(
                "failed to inspect {}: {}",
                gitignore.display(),
                err
            ));
        }
    };
    let mut block = String::new();
    block.push_str(
        "# --- Added by dux -----------------------------------------------------------\n\
         # dux seeded these entries when it initialized this repository, because the\n\
         # matching directories already existed and are almost never committed.\n\
         # Edit or remove them freely.\n",
    );
    for candidate in &kept {
        block.push('\n');
        block.push_str(candidate.comment);
        block.push('\n');
        block.push_str(candidate.dir);
        block.push_str("/\n");
    }
    file.write_all(block.as_bytes())
        .with_context(|| format!("failed to write {}", gitignore.display()))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn init_repo_dir() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let out = crate::git::test_support::git_command()
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "git init failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        dir
    }

    #[test]
    fn matched_candidates_finds_plain_and_dot_directories() {
        // Catches the seed never firing, i.e. the first agent copying the
        // dependency tree; the dot-candidate half catches a listing that
        // inherits the picker's dotfolder filter.
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir(dir.path().join("node_modules")).unwrap();
        std::fs::create_dir(dir.path().join(".venv")).unwrap();
        // A candidate-named regular FILE must not match.
        std::fs::write(dir.path().join("target"), b"not a dir").unwrap();
        let names: Vec<&str> = matched_candidates(dir.path())
            .iter()
            .map(|c| c.dir)
            .collect();
        assert_eq!(names, vec!["node_modules", ".venv"]);
    }

    #[test]
    fn seed_preserves_preexisting_gitignore_as_byte_prefix() {
        // Catches truncation data loss on a .gitignore that predates dux.
        let repo = init_repo_dir();
        std::fs::create_dir(repo.path().join("node_modules")).unwrap();
        let original = b"*.log\nsecret.txt\n".to_vec();
        std::fs::write(repo.path().join(".gitignore"), &original).unwrap();
        assert!(seed_gitignore(repo.path()).unwrap());
        let after = std::fs::read(repo.path().join(".gitignore")).unwrap();
        assert!(
            after.starts_with(&original),
            "the pre-existing bytes must remain an exact prefix"
        );
        let appended = String::from_utf8(after[original.len()..].to_vec()).unwrap();
        assert!(appended.contains("node_modules/"));
    }

    #[test]
    fn seed_adds_separator_after_file_without_trailing_newline() {
        // Catches a corrupt merged pattern like "old-last# --- Added by dux".
        let repo = init_repo_dir();
        std::fs::create_dir(repo.path().join("node_modules")).unwrap();
        std::fs::write(repo.path().join(".gitignore"), b"old-last").unwrap();
        assert!(seed_gitignore(repo.path()).unwrap());
        let after = std::fs::read_to_string(repo.path().join(".gitignore")).unwrap();
        assert!(
            after.starts_with("old-last\n"),
            "a newline separator must precede the seeded block, got: {after:?}"
        );
    }

    #[test]
    fn seed_skips_candidates_already_ignored() {
        // Catches duplicate entries accumulating across repeated seeds.
        let repo = init_repo_dir();
        std::fs::create_dir(repo.path().join("node_modules")).unwrap();
        std::fs::create_dir(repo.path().join("dist")).unwrap();
        std::fs::write(repo.path().join(".gitignore"), b"node_modules/\n").unwrap();
        assert!(seed_gitignore(repo.path()).unwrap());
        let after = std::fs::read_to_string(repo.path().join(".gitignore")).unwrap();
        assert_eq!(
            after.matches("node_modules/").count(),
            1,
            "an already-ignored candidate must not be re-added"
        );
        assert!(after.contains("dist/"));
    }

    #[test]
    fn seed_writes_nothing_when_no_candidates_match() {
        // Catches junk .gitignore files appearing in every empty init'd folder.
        let repo = init_repo_dir();
        assert!(!seed_gitignore(repo.path()).unwrap());
        assert!(!repo.path().join(".gitignore").exists());
    }

    #[test]
    fn seed_refuses_gitignore_symlink_and_leaves_target_untouched() {
        // Catches the measured follow-the-symlink escape: an append-open
        // follows a .gitignore symlink and writes outside the adopted folder.
        let repo = init_repo_dir();
        std::fs::create_dir(repo.path().join("node_modules")).unwrap();
        let outside = tempfile::tempdir().unwrap();
        let target = outside.path().join("victim.txt");
        let original = b"do not touch\n".to_vec();
        std::fs::write(&target, &original).unwrap();
        std::os::unix::fs::symlink(&target, repo.path().join(".gitignore")).unwrap();
        let err = seed_gitignore(repo.path()).unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "error must name the symlink, got: {err}"
        );
        assert_eq!(
            std::fs::read(&target).unwrap(),
            original,
            "the symlink target must be byte-identical afterward"
        );
    }

    #[test]
    fn seed_refuses_gitignore_directory() {
        // Catches the EISDIR path making a folder un-adoptable if mishandled:
        // an Err, not a panic, and no write.
        let repo = init_repo_dir();
        std::fs::create_dir(repo.path().join("node_modules")).unwrap();
        std::fs::create_dir(repo.path().join(".gitignore")).unwrap();
        let err = seed_gitignore(repo.path()).unwrap_err();
        assert!(
            err.to_string().contains("directory"),
            "error must name the directory, got: {err}"
        );
    }

    #[test]
    fn seeded_gitignore_filters_status_before_any_commit() {
        // Pins the untracked-gitignore-filters fact the feature rests on:
        // init, seed, local identity, initial commit, then status must not
        // list node_modules.
        let repo = init_repo_dir();
        std::fs::create_dir(repo.path().join("node_modules")).unwrap();
        std::fs::write(repo.path().join("node_modules").join("x.js"), b"x").unwrap();
        assert!(seed_gitignore(repo.path()).unwrap());
        for args in [
            ["config", "user.name", "test"],
            ["config", "user.email", "t@t"],
        ] {
            let out = crate::git::test_support::git_command()
                .args(args)
                .current_dir(repo.path())
                .output()
                .unwrap();
            assert!(out.status.success());
        }
        crate::git::create_initial_commit(repo.path()).unwrap();
        let out = crate::git::test_support::git_command()
            .args(["-c", "color.status=false", "status", "--porcelain"])
            .current_dir(repo.path())
            .output()
            .unwrap();
        assert!(out.status.success());
        let status = String::from_utf8_lossy(&out.stdout);
        assert!(
            !status.contains("node_modules"),
            "the seeded .gitignore must filter node_modules from status, got: {status}"
        );
    }
}
