import { describe, expect, it } from "vitest";
// @ts-expect-error - plain .mjs module, no types
import { diagramFigure, inlineSvg, renderDot } from "./graphviz.mjs";
// @ts-expect-error - plain .mjs plugin, no types
import remarkGraphviz from "./remark-graphviz.mjs";

const DOT = `digraph {
  bgcolor="transparent";
  node [shape=box style="rounded,filled" fontname="Helvetica"];
  a [class="d-gate" label="caddy"];
  b [class="d-app" label="dux"];
  a -> b;
}`;

describe("inlineSvg", () => {
  const raw = `<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "x.dtd">
<!-- Generated by graphviz -->
<svg width="300pt" height="120pt" viewBox="0.00 0.00 300.00 120.00" xmlns="http://www.w3.org/2000/svg">
<g class="node"><title>a</title><path d="M0,0"/></g>
</svg>`;

  it("drops the XML prolog so the fragment can be inlined", () => {
    const out = inlineSvg(raw);
    expect(out.startsWith("<svg")).toBe(true);
    expect(out).not.toContain("<?xml");
    expect(out).not.toContain("<!DOCTYPE");
  });

  it("drops graphviz's internal node <title> elements", () => {
    expect(inlineSvg(raw)).not.toContain("<title>");
  });

  it("replaces the fixed pt size with a responsive width, keeping the viewBox", () => {
    const out = inlineSvg(raw);
    expect(out).toContain('viewBox="0.00 0.00 300.00 120.00"');
    expect(out).toContain('width="100%"');
    expect(out).not.toContain('height="120pt"');
    expect(out).toContain('preserveAspectRatio="xMidYMid meet"');
  });

  it("publishes the intrinsic width in px and a readable minimum for CSS", () => {
    // 300pt at 96/72 is 400px; the readability floor caps the minimum at 380px.
    expect(inlineSvg(raw)).toContain("--diagram-width:400px;--diagram-min-width:380px");
  });

  it("never lets the minimum exceed the diagram's own width", () => {
    const narrow = raw.replace(/300/g, "120");
    // 120pt is 160px, which is narrower than the floor, so the floor gives way.
    expect(inlineSvg(narrow)).toContain("--diagram-width:160px;--diagram-min-width:160px");
  });

  it("labels the drawing when given one, and marks it presentational otherwise", () => {
    expect(inlineSvg(raw, { label: 'a "path"' })).toContain('aria-label="a &quot;path&quot;"');
    expect(inlineSvg(raw)).toContain('role="presentation"');
  });

  it("refuses markup that is not a graphviz SVG", () => {
    expect(() => inlineSvg("nope")).toThrow(/no <svg>/);
    expect(() => inlineSvg("<svg width='1pt'></svg>")).toThrow(/viewBox/);
  });
});

describe("diagramFigure", () => {
  it("wraps the drawing in a scroll container and omits an empty caption", () => {
    expect(diagramFigure("<svg/>")).toBe(
      '<figure class="diagram not-prose"><div class="diagram-scroll"><svg/></div></figure>',
    );
    expect(diagramFigure("<svg/>", "Who talks to what.")).toContain(
      '<figcaption class="diagram-caption">Who talks to what.</figcaption>',
    );
  });
});

describe("renderDot", () => {
  it("lays out DOT to SVG in plain node, with no browser", async () => {
    const svg = await renderDot(DOT);
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg).toContain("</svg>");
  });

  it("carries the DOT class names through so CSS owns the palette", async () => {
    const svg = await renderDot(DOT);
    // Graphviz escapes the hyphen in class names as a numeric entity.
    expect(svg.replace(/&#45;/g, "-")).toContain('class="node d-gate"');
    expect(svg.replace(/&#45;/g, "-")).toContain('class="node d-app"');
  });
});

describe("remark-graphviz", () => {
  async function run(lang: string, meta?: string) {
    const node: any = { type: "code", lang, meta, value: DOT };
    await remarkGraphviz()({ type: "root", children: [node] });
    return node;
  }

  it("replaces a ```dot block with a rendered figure", async () => {
    const node = await run("dot", "The path a request takes.");
    expect(node.type).toBe("html");
    expect(node.value).toContain('<figure class="diagram not-prose">');
    expect(node.value).toContain("<svg");
    expect(node.value).toContain("The path a request takes.");
    expect(node.lang).toBeUndefined();
  });

  it("accepts the graphviz alias and needs no caption", async () => {
    const node = await run("graphviz");
    expect(node.type).toBe("html");
    expect(node.value).not.toContain("figcaption");
  });

  it("leaves every other language alone", async () => {
    const node = await run("bash");
    expect(node.type).toBe("code");
    expect(node.value).toBe(DOT);
  });
});
